# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [whois, marines1]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username sandersonfarms
issuehunt: # Replace with a single IssueHunt username failure10
otechie: # Replace with a single Otechie username vampus
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://pbs.org','https://go.gale.com/ps/anonymous?id=GALE%7CA155735542&sid=googleScholar&v=2.1&it=r&linkaccess=abs&issn=10639330&p=AONE&sw=w','https://chime.com','https://www.eonline.com/news/1076568/latin-pop-primer-the-15-female-artists-you-need-to-know-now','https://Whois.int','https://uso.org','https://'https://www.coronavirus.gov/']
